---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders/finalizers
  verbs:
  - update
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders/status
  verbs:
  - get
  - patch
  - update
